name: Upload Resume to Naukri

on:
  schedule:
    - cron: "30 2 * * *"   # 8:00 AM IST
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    env:
      NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
      NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Upload Resume
        run: python naukri.py
